[project]
name = "test_fast"
version = "0.1.0"
description = "FastMCP test project"
requires-python = ">=3.10"
dependencies = [
    "fastmcp",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 

[tool.hatch.build.targets.wheel]
packages = ["."] 